prompt: /Users/zivtzur/PycharmProjects/My_agent/configs/prompts/keywords.txt
program_params:
  program_goal: מטרה מרכזית
  program_description: תקציר תוכנית
subject_params:
  mandatory_keywords: mandatory_keywords
  general_keywords: keywords
special_params: ''